# Generated by Django 6.1 on 2026-08-11 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('pattern', 'Patrón detectado'), ('achievement', 'Logro'), ('suggestion', 'Sugerencia'), ('weekly_summary', 'Resumen semanal')], max_length=20)),
                ('text', models.TextField()),
                ('action_label', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dismissed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FastingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('target_hours', models.PositiveIntegerField(default=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fasting_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Desayuno'), ('lunch', 'Almuerzo'), ('snack', 'Merienda'), ('dinner', 'Cena')], max_length=16)),
                ('source', models.CharField(choices=[('photo_ai', 'Foto con IA'), ('barcode', 'Código de barras'), ('search', 'Búsqueda'), ('voice', 'Voz'), ('saved_recipe', 'Receta guardada')], default='search', max_length=16)),
                ('logged_at', models.DateTimeField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='meal_photos/')),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('quality_score', models.CharField(blank=True, max_length=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('grams', models.FloatField(blank=True, null=True)),
                ('kcal', models.PositiveIntegerField()),
                ('protein_g', models.FloatField(default=0)),
                ('carbs_g', models.FloatField(default=0)),
                ('fat_g', models.FloatField(default=0)),
                ('fiber_g', models.FloatField(default=0)),
                ('iron_mg', models.FloatField(default=0)),
                ('calcium_mg', models.FloatField(default=0)),
                ('vitamin_c_mg', models.FloatField(default=0)),
                ('vitamin_d_ug', models.FloatField(default=0)),
                ('sodium_mg', models.FloatField(default=0)),
                ('detection_confidence', models.FloatField(blank=True, null=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nutrition.meal')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(choices=[('lose', 'Bajar de peso'), ('maintain', 'Mantener mi peso'), ('gain', 'Ganar masa muscular')], default='maintain', max_length=16)),
                ('daily_kcal_target', models.PositiveIntegerField(default=2000)),
                ('protein_target_g', models.PositiveIntegerField(default=140)),
                ('carbs_target_g', models.PositiveIntegerField(default=220)),
                ('fat_target_g', models.PositiveIntegerField(default=70)),
                ('water_target_glasses', models.PositiveIntegerField(default=8)),
                ('fasting_window_hours', models.PositiveIntegerField(default=16)),
                ('current_weight_kg', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('kcal', models.PositiveIntegerField()),
                ('protein_g', models.FloatField(default=0)),
                ('carbs_g', models.FloatField(default=0)),
                ('fat_g', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight_kg', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='WaterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('glasses', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
