# Generated by Django 6.1 on 2026-08-11 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'Sedentario (poco o nada de ejercicio)'), ('light', 'Actividad leve (1-3 días/semana)'), ('moderate', 'Actividad moderada (3-5 días/semana)'), ('active', 'Activo (6-7 días/semana)'), ('very_active', 'Muy activo (entrenamiento intenso diario)')], default='moderate', max_length=16),
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='height_cm',
            field=models.PositiveIntegerField(default=170),
        ),
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('m', 'Masculino'), ('f', 'Femenino')], default='m', max_length=1),
        ),
    ]
