# Generated by Django 6.1 on 2026-08-11 23:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_chatmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedrecipe',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='savedrecipe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedrecipe',
            name='ingredients',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='savedrecipe',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='savedrecipe',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Desayuno'), ('lunch', 'Almuerzo'), ('snack', 'Merienda'), ('dinner', 'Cena'), ('any', 'Cualquier momento')], default='any', max_length=16),
        ),
        migrations.AlterField(
            model_name='savedrecipe',
            name='kcal',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
