# Generated by Django 6.1 on 2026-08-12 01:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0004_alter_savedrecipe_options_savedrecipe_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weightlog',
            unique_together={('user', 'date')},
        ),
    ]
