# Generated by Django 6.1 on 2026-08-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0005_alter_weightlog_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='target_weight_kg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
