# Generated by Django 6.1 on 2026-08-13 02:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0008_alter_fooditem_calcium_mg_alter_fooditem_carbs_g_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='daily_steps_goal',
            field=models.PositiveIntegerField(default=8000, validators=[django.core.validators.MinValueValidator(1000)]),
        ),
    ]
