"""
Django settings for nutria_backend project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')

GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY', '')
GEMINI_MODEL = os.environ.get('GEMINI_MODEL', 'gemini-3.5-flash')

# Límites del plan free — usuarios Premium (Subscription.is_active) no los tocan.
COACH_CHAT_FREE_DAILY_LIMIT = int(os.environ.get('COACH_CHAT_FREE_DAILY_LIMIT', 5))
SCAN_PHOTO_FREE_DAILY_LIMIT = int(os.environ.get('SCAN_PHOTO_FREE_DAILY_LIMIT', 3))
RECIPES_FREE_LIMIT = int(os.environ.get('RECIPES_FREE_LIMIT', 5))

# Mercado Pago — pago único por período (no suscripción con renovación
# automática). Access Token de PRODUCCIÓN, sacado del panel de developers.
MERCADOPAGO_ACCESS_TOKEN = os.environ.get('MERCADOPAGO_ACCESS_TOKEN', '')
PREMIUM_PRICE_MONTHLY = int(os.environ.get('PREMIUM_PRICE_MONTHLY', 6500))
PREMIUM_PRICE_ANNUAL = int(os.environ.get('PREMIUM_PRICE_ANNUAL', 54000))  # $4.500/mes x 12
# Dominio público de la app — para armar los back_urls que le pasamos a MP.
PUBLIC_BASE_URL = os.environ.get('PUBLIC_BASE_URL', 'https://frfit-backend.onrender.com')

# Google Sign-In — el client ID "Web" (no el de Android). Es el "audience"
# contra el que se valida el id_token que manda la app; google_sign_in en
# Android lo emite con este client ID cuando se configura serverClientId.
GOOGLE_OAUTH_CLIENT_ID = os.environ.get(
    'GOOGLE_OAUTH_CLIENT_ID',
    '885557456922-27jf8e3te2dljetm7m7j0utfmig98pej.apps.googleusercontent.com',
)


# SECURITY WARNING: keep the secret key used in production secret!
# En local, si no está en el .env, se usa el valor de desarrollo de siempre.
# En producción, DJANGO_SECRET_KEY es obligatoria (ver .env.example).
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-=^iti^xsr%q9u=#%f!xe(za+lzrrlij*24#(dlm012*by%wgjq',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# En local, '*' habilita acceso desde cualquier IP de la red (celular real
# incluido). En producción, DJANGO_ALLOWED_HOSTS tiene que traer el dominio
# real separado por comas (ej. "nutria-backend.onrender.com").
ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', '*').split(',')

if not DEBUG:
    # Render termina el HTTPS en su proxy y reenvía por HTTP interno con este
    # header — sin esto, SECURE_SSL_REDIRECT entra en loop infinito de
    # redirects porque Django nunca ve la conexión como "segura".
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 7  # 1 semana; se puede subir con el tiempo
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'nutrition',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# La app Flutter no corre en un navegador, no hay origen a validar — pero si
# el día de mañana se suma un panel web propio, restringir esto a los
# dominios reales en vez de allow-all.
CORS_ALLOW_ALL_ORIGINS = True

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

ROOT_URLCONF = 'nutria_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'nutria_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# En local usa SQLite como siempre. En producción, DATABASE_URL la provee
# Render automáticamente al conectar una base Postgres al servicio.
DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'es-ar'

# La app y sus usuarios son de Argentina: usar esta zona (no UTC) para que los
# filtros por fecha (logged_at__date, etc.) coincidan con el "día de hoy" real
# del usuario en vez de desfasarse a partir de las 21hs (cuando en UTC ya es
# el día siguiente).
TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'
        if not DEBUG
        else 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
}

# OJO: en el free tier de Render el disco no es persistente — las fotos de
# comida (MEDIA_ROOT) se pierden en cada redeploy. Sirve para probar el
# deploy, pero para producción real hay que mover esto a un storage externo
# (ej. Cloudflare R2 / S3) antes de tener usuarios reales subiendo fotos.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
# Por defecto los emails (ej. "olvidé mi contraseña") se imprimen en la consola
# del server en vez de enviarse — sirve para probar, pero para que lleguen de
# verdad hay que configurar un proveedor SMTP real (ver EMAIL_* en .env.example)
# y setear EMAIL_BACKEND a 'django.core.mail.backends.smtp.EmailBackend'.

EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'FRfit <no-reply@frfit.app>')
